<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CreateIngredientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ingredients = [
            ['name' => 'Varškė'],
            ['name' => 'Kiaušinis'],
            ['name' => 'Grietinė'],
            ['name' => 'Cukrus'],
            ['name' => 'Rudasis cukrus'],
            ['name' => 'Cukraus pudra'],
            ['name' => 'Vanilinis cukrus'],
            ['name' => 'Vištienos kojelė'],
            ['name' => 'Vištienos sparneliai'],
            ['name' => 'Vištienos krūtinėlė'],
            ['name' => 'Vištienos filė'],
            ['name' => 'Kiaulienos filė'],
            ['name' => 'Kiaulienos sprandinė'],
            ['name' => 'Kiaulienos kumpis'],
            ['name' => 'Jautienos faršas'],
            ['name' => 'Menkės filė'],
            ['name' => 'Silkės filė'],
            ['name' => 'lašišos'],
            ['name' => 'Šoninė'],
            ['name' => 'Lašiniai'],
            ['name' => 'Alyvuogių aliejus'],
            ['name' => 'Alyvuogės'],
            ['name' => 'Rapsų aliejus'],
            ['name' => 'Aliejus'],
            ['name' => 'Svogūnai'],
            ['name' => 'Morkos'],
            ['name' => 'Cukinijos'],
            ['name' => 'Bulvės'],
            ['name' => 'Druska'],
            ['name' => 'Pipirai'],
            ['name' => 'Čili pipirai'],
            ['name' => 'Česnakas'],
            ['name' => 'Lauro lapai'],
            ['name' => 'Rauginti agurkai'],
            ['name' => 'Paprikos'],
            ['name' => 'Aitrios paprikos'],
            ['name' => 'Pomidorų padažas'],
            ['name' => 'Konservuoti pomidorai'],
            ['name' => 'Saulėje džiovinti pomidorai'],
            ['name' => 'Miltai'],
            ['name' => 'Kvietiniai miltai'],
            ['name' => 'Ryžių miltai'],
            ['name' => 'Kukurūzų miltai'],
            ['name' => 'Kepimo milteliai'],
            ['name' => 'Vaninilis cukrus'],
            ['name' => 'Meduoliai'],
            ['name' => 'Želatinas'],
            ['name' => 'Kukurūzų dripsniai'],
            ['name' => 'Kondensuotas pienas'],
            ['name' => 'Migdolas'],
            ['name' => 'Sezamo sėklos'],
            ['name' => 'Sviestas'],
            ['name' => 'Margarinas'],
            ['name' => 'Pienas'],
            ['name' => 'Baltasis šokoladas'],
            ['name' => 'Juodasis šokoladas'],
            ['name' => 'Grietinėlė'],
            ['name' => 'Sausainiai'],
            ['name' => 'Džiovinti vaisai'],
            ['name' => 'Manų kruopos'],
            ['name' => 'Jogurtas'],
            ['name' => 'Kefyras'],
            ['name' => 'Lazdyno riešutai'],
            ['name' => 'Graikiški riešutai'],
            ['name' => 'Kedro rieštutai'],
            ['name' => 'Muškato rieštutai'], // ?
            ['name' => 'Muskatas'],   //recepte parašyta malto Muskato, kitame recepte - riešutai
            ['name' => 'Kardamonas'], //recepte parašyta malto Kardamono
            ['name' => 'Vanduo'],
            ['name' => 'Cinamona'],
            ['name' => 'Maltas cinamona'],
            ['name' => 'Tirpi kava'],
            ['name' => 'Sodos'],
            ['name' => 'Pudingas'],
            ['name' => 'Citrina'],
            ['name' => 'Apelsinai'],
            ['name' => 'Bananai'],
            ['name' => 'Mandarinai'],
            ['name' => 'Konservuoti ananasai'],
            ['name' => 'Obuoliai'],
            ['name' => 'Braškės'],
            ['name' => 'Vyšnės'],
            ['name' => 'Avietės'],
            ['name' => 'Mėlynės'],
            ['name' => 'Brokoliai'],
            ['name' => 'Krakmolas'],
            ['name' => 'Kakavos'], //kakavos milteliai
            ['name' => 'Markasponės sūris'],
            ['name' => 'Mocarelos sūris'],
            ['name' => 'Parmazeno sūris'],
            ['name' => 'Sūris'],
            ['name' => 'Actas'],
            ['name' => 'Medus'],
            ['name' => 'Imbieras'],
            ['name' => 'Žėlė'],
            ['name' => 'Konvervuotos vyšnios'],
            ['name' => 'Krekeriai'],
            ['name' => 'Vanilė'],
            ['name' => 'Šokoladas Mars'],
            ['name' => 'Mėtos'],  // Ar Mėtų lapai?
            ['name' => 'Kokosų drožlės'],
            ['name' => 'Mielės'],
            ['name' => 'Bazilikai'],
            ['name' => 'Pesto padažas'],
            ['name' => 'Petražolės'],
            ['name' => 'Provanso žolių mišinys'],
            ['name' => 'Majonezas'],
            ['name' => 'Juodieji malti pipirai'],
            ['name' => 'Raudonėlai'],
            ['name' => 'Mėsos prieskoniai'],
            ['name' => 'Čili prieskoniai'],
            ['name' => 'Žuvies prieskoniai'],
            ['name' => 'Saliero stiebas'],
            ['name' => 'Gvazdikėliai'],
            ['name' => 'Lazanijos lakštai'],
            ['name' => 'Krabų lazdelės'],
            ['name' => 'Krapai'],
            ['name' => 'Kalendra'],
            ['name' => 'Daržovių sultinys'],
            ['name' => 'Burokėliai'],
            ['name' => 'Garstyčios'],
            ['name' => 'Taukai'],
            ['name' => 'Mairūmas'],
            ['name' => 'Baltasis vynas'],
            ['name' => 'Čiobreliai'],
            ['name' => 'Džiūvėsėliai'],
            ['name' => 'Pupelės'],
        ];

        foreach ($ingredients as $key => $value) {
            User::create($value);
        }
    }
}
